-- Generated by scripts/generate-seed.mjs. Local reset only.
-- 45 fixtures per round: 15 easy, 20 medium, 10 hard.
-- Repeated concepts exercise pool mechanics; difficulty is synthetic, not classroom-ready.
begin;
insert into public.rounds values
(1,'L1','vault-of-keys','The Vault of Keys'),
(2,'L2','guild-city','Guild City'),
(3,'L3','cipher-lock','The Cipher Lock'),
(4,'L4','alchemists-workshop','The Alchemist’s Workshop'),
(5,'L5','card-table','The Card Table'),
(6,'L6','orbit-grand-prix','Orbit Grand Prix'),
(7,'L7','nesting-temple','The Nesting Temple'),
(8,'L8','noir-bureau','Noir Bureau'),
(9,'L10','cartographers-finale','The Cartographer’s Finale');
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','easy','Which key identifies every row?','A primary key uniquely identifies a row and cannot contain NULL.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Primary key"}'::jsonb,true,null),
('{"text":"Foreign key"}'::jsonb,false,'Confuses Primary key with Foreign key'),
('{"text":"Nullable column"}'::jsonb,false,'Confuses Primary key with Nullable column'),
('{"text":"Default value"}'::jsonb,false,'Confuses Primary key with Default value')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','easy','Which key references another table?','A foreign key requires a matching referenced key, unless its value is NULL and allowed.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Foreign key"}'::jsonb,true,null),
('{"text":"Candidate key"}'::jsonb,false,'Confuses Foreign key with Candidate key'),
('{"text":"Superkey"}'::jsonb,false,'Confuses Foreign key with Superkey'),
('{"text":"Composite primary key"}'::jsonb,false,'Confuses Foreign key with Composite primary key')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','easy','Which constraint forbids missing values?','NOT NULL rejects a NULL value.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"NOT NULL"}'::jsonb,true,null),
('{"text":"UNIQUE"}'::jsonb,false,'Confuses NOT NULL with UNIQUE'),
('{"text":"DEFAULT"}'::jsonb,false,'Confuses NOT NULL with DEFAULT'),
('{"text":"FOREIGN KEY"}'::jsonb,false,'Confuses NOT NULL with FOREIGN KEY')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','easy','Which constraint rejects duplicate non-NULL values?','UNIQUE disallows duplicate non-NULL values.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"UNIQUE"}'::jsonb,true,null),
('{"text":"NOT NULL"}'::jsonb,false,'Confuses UNIQUE with NOT NULL'),
('{"text":"DEFAULT"}'::jsonb,false,'Confuses UNIQUE with DEFAULT'),
('{"text":"CHECK (true)"}'::jsonb,false,'Confuses UNIQUE with CHECK (true)')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','easy','What is a minimal superkey?','A candidate key is a superkey with no redundant attributes.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Candidate key"}'::jsonb,true,null),
('{"text":"Foreign key"}'::jsonb,false,'Confuses Candidate key with Foreign key'),
('{"text":"Any attribute"}'::jsonb,false,'Confuses Candidate key with Any attribute'),
('{"text":"Default key"}'::jsonb,false,'Confuses Candidate key with Default key')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','easy','A key uses two columns. What is it?','A composite key consists of more than one column.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Composite key"}'::jsonb,true,null),
('{"text":"Partial value"}'::jsonb,false,'Confuses Composite key with Partial value'),
('{"text":"Nullable key"}'::jsonb,false,'Confuses Composite key with Nullable key'),
('{"text":"Scalar key"}'::jsonb,false,'Confuses Composite key with Scalar key')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','easy','What describes a table’s structure?','A schema defines structure, including relations, attributes and constraints.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Schema"}'::jsonb,true,null),
('{"text":"Current row count"}'::jsonb,false,'Confuses Schema with Current row count'),
('{"text":"Query result"}'::jsonb,false,'Confuses Schema with Query result'),
('{"text":"Transaction log"}'::jsonb,false,'Confuses Schema with Transaction log')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','easy','Which type stores true or false?','PostgreSQL boolean stores true, false, or NULL if permitted.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"boolean"}'::jsonb,true,null),
('{"text":"integer"}'::jsonb,false,'Confuses boolean with integer'),
('{"text":"date"}'::jsonb,false,'Confuses boolean with date'),
('{"text":"text"}'::jsonb,false,'Confuses boolean with text')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','easy','Which type stores calendar dates?','The date type represents a calendar date.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"date"}'::jsonb,true,null),
('{"text":"boolean"}'::jsonb,false,'Confuses date with boolean'),
('{"text":"integer"}'::jsonb,false,'Confuses date with integer'),
('{"text":"bytea"}'::jsonb,false,'Confuses date with bytea')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','easy','Which constraint checks positive prices?','CHECK evaluates a predicate; add NOT NULL if missing prices must also be forbidden.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"CHECK (price > 0)"}'::jsonb,true,null),
('{"text":"UNIQUE (price)"}'::jsonb,false,'Confuses CHECK (price > 0) with UNIQUE (price)'),
('{"text":"DEFAULT 0"}'::jsonb,false,'Confuses CHECK (price > 0) with DEFAULT 0'),
('{"text":"PRIMARY KEY (price)"}'::jsonb,false,'Confuses CHECK (price > 0) with PRIMARY KEY (price)')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','easy','Can a primary-key column contain NULL?','Every primary-key column is implicitly NOT NULL.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"No"}'::jsonb,true,null),
('{"text":"Always"}'::jsonb,false,'Confuses No with Always'),
('{"text":"Only once"}'::jsonb,false,'Confuses No with Only once'),
('{"text":"Only in empty strings"}'::jsonb,false,'Confuses No with Only in empty strings')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','easy','Can a table have several candidate keys?','Several minimal attribute sets may each uniquely identify a row.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Yes"}'::jsonb,true,null),
('{"text":"Never"}'::jsonb,false,'Confuses Yes with Never'),
('{"text":"Only without rows"}'::jsonb,false,'Confuses Yes with Only without rows'),
('{"text":"Only with NULLs"}'::jsonb,false,'Confuses Yes with Only with NULLs')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','easy','Does adding columns preserve a superkey?','A superset of a superkey still uniquely identifies a row.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Yes"}'::jsonb,true,null),
('{"text":"Never"}'::jsonb,false,'Confuses Yes with Never'),
('{"text":"Only for text columns"}'::jsonb,false,'Confuses Yes with Only for text columns'),
('{"text":"Only for empty tables"}'::jsonb,false,'Confuses Yes with Only for empty tables')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','easy','Must every foreign-key value be unique?','Many referencing rows may refer to the same parent row.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"No"}'::jsonb,true,null),
('{"text":"Always"}'::jsonb,false,'Confuses No with Always'),
('{"text":"Only integers"}'::jsonb,false,'Confuses No with Only integers'),
('{"text":"Only strings"}'::jsonb,false,'Confuses No with Only strings')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','easy','What does entity integrity require?','Entity integrity requires valid non-NULL primary-key identification.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Primary keys cannot be NULL"}'::jsonb,true,null),
('{"text":"Every column must be unique"}'::jsonb,false,'Confuses Primary keys cannot be NULL with Every column must be unique'),
('{"text":"Every table needs a foreign key"}'::jsonb,false,'Confuses Primary keys cannot be NULL with Every table needs a foreign key'),
('{"text":"Every column must have defaults"}'::jsonb,false,'Confuses Primary keys cannot be NULL with Every column must have defaults')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','At the gate: Which key identifies every row?','A primary key uniquely identifies a row and cannot contain NULL.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Primary key"}'::jsonb,true,null),
('{"text":"Foreign key"}'::jsonb,false,'Confuses Primary key with Foreign key'),
('{"text":"Nullable column"}'::jsonb,false,'Confuses Primary key with Nullable column'),
('{"text":"Default value"}'::jsonb,false,'Confuses Primary key with Default value')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','At the gate: Which key references another table?','A foreign key requires a matching referenced key, unless its value is NULL and allowed.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Foreign key"}'::jsonb,true,null),
('{"text":"Candidate key"}'::jsonb,false,'Confuses Foreign key with Candidate key'),
('{"text":"Superkey"}'::jsonb,false,'Confuses Foreign key with Superkey'),
('{"text":"Composite primary key"}'::jsonb,false,'Confuses Foreign key with Composite primary key')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','At the gate: Which constraint forbids missing values?','NOT NULL rejects a NULL value.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"NOT NULL"}'::jsonb,true,null),
('{"text":"UNIQUE"}'::jsonb,false,'Confuses NOT NULL with UNIQUE'),
('{"text":"DEFAULT"}'::jsonb,false,'Confuses NOT NULL with DEFAULT'),
('{"text":"FOREIGN KEY"}'::jsonb,false,'Confuses NOT NULL with FOREIGN KEY')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','At the gate: Which constraint rejects duplicate non-NULL values?','UNIQUE disallows duplicate non-NULL values.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"UNIQUE"}'::jsonb,true,null),
('{"text":"NOT NULL"}'::jsonb,false,'Confuses UNIQUE with NOT NULL'),
('{"text":"DEFAULT"}'::jsonb,false,'Confuses UNIQUE with DEFAULT'),
('{"text":"CHECK (true)"}'::jsonb,false,'Confuses UNIQUE with CHECK (true)')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','At the gate: What is a minimal superkey?','A candidate key is a superkey with no redundant attributes.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Candidate key"}'::jsonb,true,null),
('{"text":"Foreign key"}'::jsonb,false,'Confuses Candidate key with Foreign key'),
('{"text":"Any attribute"}'::jsonb,false,'Confuses Candidate key with Any attribute'),
('{"text":"Default key"}'::jsonb,false,'Confuses Candidate key with Default key')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','At the gate: A key uses two columns. What is it?','A composite key consists of more than one column.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Composite key"}'::jsonb,true,null),
('{"text":"Partial value"}'::jsonb,false,'Confuses Composite key with Partial value'),
('{"text":"Nullable key"}'::jsonb,false,'Confuses Composite key with Nullable key'),
('{"text":"Scalar key"}'::jsonb,false,'Confuses Composite key with Scalar key')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','At the gate: What describes a table’s structure?','A schema defines structure, including relations, attributes and constraints.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Schema"}'::jsonb,true,null),
('{"text":"Current row count"}'::jsonb,false,'Confuses Schema with Current row count'),
('{"text":"Query result"}'::jsonb,false,'Confuses Schema with Query result'),
('{"text":"Transaction log"}'::jsonb,false,'Confuses Schema with Transaction log')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','At the gate: Which type stores true or false?','PostgreSQL boolean stores true, false, or NULL if permitted.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"boolean"}'::jsonb,true,null),
('{"text":"integer"}'::jsonb,false,'Confuses boolean with integer'),
('{"text":"date"}'::jsonb,false,'Confuses boolean with date'),
('{"text":"text"}'::jsonb,false,'Confuses boolean with text')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','At the gate: Which type stores calendar dates?','The date type represents a calendar date.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"date"}'::jsonb,true,null),
('{"text":"boolean"}'::jsonb,false,'Confuses date with boolean'),
('{"text":"integer"}'::jsonb,false,'Confuses date with integer'),
('{"text":"bytea"}'::jsonb,false,'Confuses date with bytea')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','At the gate: Which constraint checks positive prices?','CHECK evaluates a predicate; add NOT NULL if missing prices must also be forbidden.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"CHECK (price > 0)"}'::jsonb,true,null),
('{"text":"UNIQUE (price)"}'::jsonb,false,'Confuses CHECK (price > 0) with UNIQUE (price)'),
('{"text":"DEFAULT 0"}'::jsonb,false,'Confuses CHECK (price > 0) with DEFAULT 0'),
('{"text":"PRIMARY KEY (price)"}'::jsonb,false,'Confuses CHECK (price > 0) with PRIMARY KEY (price)')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','At the gate: Can a primary-key column contain NULL?','Every primary-key column is implicitly NOT NULL.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"No"}'::jsonb,true,null),
('{"text":"Always"}'::jsonb,false,'Confuses No with Always'),
('{"text":"Only once"}'::jsonb,false,'Confuses No with Only once'),
('{"text":"Only in empty strings"}'::jsonb,false,'Confuses No with Only in empty strings')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','At the gate: Can a table have several candidate keys?','Several minimal attribute sets may each uniquely identify a row.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Yes"}'::jsonb,true,null),
('{"text":"Never"}'::jsonb,false,'Confuses Yes with Never'),
('{"text":"Only without rows"}'::jsonb,false,'Confuses Yes with Only without rows'),
('{"text":"Only with NULLs"}'::jsonb,false,'Confuses Yes with Only with NULLs')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','At the gate: Does adding columns preserve a superkey?','A superset of a superkey still uniquely identifies a row.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Yes"}'::jsonb,true,null),
('{"text":"Never"}'::jsonb,false,'Confuses Yes with Never'),
('{"text":"Only for text columns"}'::jsonb,false,'Confuses Yes with Only for text columns'),
('{"text":"Only for empty tables"}'::jsonb,false,'Confuses Yes with Only for empty tables')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','At the gate: Must every foreign-key value be unique?','Many referencing rows may refer to the same parent row.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"No"}'::jsonb,true,null),
('{"text":"Always"}'::jsonb,false,'Confuses No with Always'),
('{"text":"Only integers"}'::jsonb,false,'Confuses No with Only integers'),
('{"text":"Only strings"}'::jsonb,false,'Confuses No with Only strings')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','At the gate: What does entity integrity require?','Entity integrity requires valid non-NULL primary-key identification.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Primary keys cannot be NULL"}'::jsonb,true,null),
('{"text":"Every column must be unique"}'::jsonb,false,'Confuses Primary keys cannot be NULL with Every column must be unique'),
('{"text":"Every table needs a foreign key"}'::jsonb,false,'Confuses Primary keys cannot be NULL with Every table needs a foreign key'),
('{"text":"Every column must have defaults"}'::jsonb,false,'Confuses Primary keys cannot be NULL with Every column must have defaults')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','Inside the vault: Which key identifies every row?','A primary key uniquely identifies a row and cannot contain NULL.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Primary key"}'::jsonb,true,null),
('{"text":"Foreign key"}'::jsonb,false,'Confuses Primary key with Foreign key'),
('{"text":"Nullable column"}'::jsonb,false,'Confuses Primary key with Nullable column'),
('{"text":"Default value"}'::jsonb,false,'Confuses Primary key with Default value')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','Inside the vault: Which key references another table?','A foreign key requires a matching referenced key, unless its value is NULL and allowed.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Foreign key"}'::jsonb,true,null),
('{"text":"Candidate key"}'::jsonb,false,'Confuses Foreign key with Candidate key'),
('{"text":"Superkey"}'::jsonb,false,'Confuses Foreign key with Superkey'),
('{"text":"Composite primary key"}'::jsonb,false,'Confuses Foreign key with Composite primary key')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','Inside the vault: Which constraint forbids missing values?','NOT NULL rejects a NULL value.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"NOT NULL"}'::jsonb,true,null),
('{"text":"UNIQUE"}'::jsonb,false,'Confuses NOT NULL with UNIQUE'),
('{"text":"DEFAULT"}'::jsonb,false,'Confuses NOT NULL with DEFAULT'),
('{"text":"FOREIGN KEY"}'::jsonb,false,'Confuses NOT NULL with FOREIGN KEY')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','Inside the vault: Which constraint rejects duplicate non-NULL values?','UNIQUE disallows duplicate non-NULL values.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"UNIQUE"}'::jsonb,true,null),
('{"text":"NOT NULL"}'::jsonb,false,'Confuses UNIQUE with NOT NULL'),
('{"text":"DEFAULT"}'::jsonb,false,'Confuses UNIQUE with DEFAULT'),
('{"text":"CHECK (true)"}'::jsonb,false,'Confuses UNIQUE with CHECK (true)')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','medium','Inside the vault: What is a minimal superkey?','A candidate key is a superkey with no redundant attributes.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Candidate key"}'::jsonb,true,null),
('{"text":"Foreign key"}'::jsonb,false,'Confuses Candidate key with Foreign key'),
('{"text":"Any attribute"}'::jsonb,false,'Confuses Candidate key with Any attribute'),
('{"text":"Default key"}'::jsonb,false,'Confuses Candidate key with Default key')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','hard','Inside the vault: A key uses two columns. What is it?','A composite key consists of more than one column.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Composite key"}'::jsonb,true,null),
('{"text":"Partial value"}'::jsonb,false,'Confuses Composite key with Partial value'),
('{"text":"Nullable key"}'::jsonb,false,'Confuses Composite key with Nullable key'),
('{"text":"Scalar key"}'::jsonb,false,'Confuses Composite key with Scalar key')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','hard','Inside the vault: What describes a table’s structure?','A schema defines structure, including relations, attributes and constraints.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Schema"}'::jsonb,true,null),
('{"text":"Current row count"}'::jsonb,false,'Confuses Schema with Current row count'),
('{"text":"Query result"}'::jsonb,false,'Confuses Schema with Query result'),
('{"text":"Transaction log"}'::jsonb,false,'Confuses Schema with Transaction log')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','hard','Inside the vault: Which type stores true or false?','PostgreSQL boolean stores true, false, or NULL if permitted.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"boolean"}'::jsonb,true,null),
('{"text":"integer"}'::jsonb,false,'Confuses boolean with integer'),
('{"text":"date"}'::jsonb,false,'Confuses boolean with date'),
('{"text":"text"}'::jsonb,false,'Confuses boolean with text')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','hard','Inside the vault: Which type stores calendar dates?','The date type represents a calendar date.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"date"}'::jsonb,true,null),
('{"text":"boolean"}'::jsonb,false,'Confuses date with boolean'),
('{"text":"integer"}'::jsonb,false,'Confuses date with integer'),
('{"text":"bytea"}'::jsonb,false,'Confuses date with bytea')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','hard','Inside the vault: Which constraint checks positive prices?','CHECK evaluates a predicate; add NOT NULL if missing prices must also be forbidden.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"CHECK (price > 0)"}'::jsonb,true,null),
('{"text":"UNIQUE (price)"}'::jsonb,false,'Confuses CHECK (price > 0) with UNIQUE (price)'),
('{"text":"DEFAULT 0"}'::jsonb,false,'Confuses CHECK (price > 0) with DEFAULT 0'),
('{"text":"PRIMARY KEY (price)"}'::jsonb,false,'Confuses CHECK (price > 0) with PRIMARY KEY (price)')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','hard','Inside the vault: Can a primary-key column contain NULL?','Every primary-key column is implicitly NOT NULL.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"No"}'::jsonb,true,null),
('{"text":"Always"}'::jsonb,false,'Confuses No with Always'),
('{"text":"Only once"}'::jsonb,false,'Confuses No with Only once'),
('{"text":"Only in empty strings"}'::jsonb,false,'Confuses No with Only in empty strings')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','hard','Inside the vault: Can a table have several candidate keys?','Several minimal attribute sets may each uniquely identify a row.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Yes"}'::jsonb,true,null),
('{"text":"Never"}'::jsonb,false,'Confuses Yes with Never'),
('{"text":"Only without rows"}'::jsonb,false,'Confuses Yes with Only without rows'),
('{"text":"Only with NULLs"}'::jsonb,false,'Confuses Yes with Only with NULLs')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','hard','Inside the vault: Does adding columns preserve a superkey?','A superset of a superkey still uniquely identifies a row.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Yes"}'::jsonb,true,null),
('{"text":"Never"}'::jsonb,false,'Confuses Yes with Never'),
('{"text":"Only for text columns"}'::jsonb,false,'Confuses Yes with Only for text columns'),
('{"text":"Only for empty tables"}'::jsonb,false,'Confuses Yes with Only for empty tables')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','hard','Inside the vault: Must every foreign-key value be unique?','Many referencing rows may refer to the same parent row.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"No"}'::jsonb,true,null),
('{"text":"Always"}'::jsonb,false,'Confuses No with Always'),
('{"text":"Only integers"}'::jsonb,false,'Confuses No with Only integers'),
('{"text":"Only strings"}'::jsonb,false,'Confuses No with Only strings')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(1,'concept','hard','Inside the vault: What does entity integrity require?','Entity integrity requires valid non-NULL primary-key identification.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"Primary keys cannot be NULL"}'::jsonb,true,null),
('{"text":"Every column must be unique"}'::jsonb,false,'Confuses Primary keys cannot be NULL with Every column must be unique'),
('{"text":"Every table needs a foreign key"}'::jsonb,false,'Confuses Primary keys cannot be NULL with Every table needs a foreign key'),
('{"text":"Every column must have defaults"}'::jsonb,false,'Confuses Primary keys cannot be NULL with Every column must have defaults')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','easy','Which command creates a table?','CREATE TABLE defines a new relation and belongs to DDL.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"CREATE TABLE"}'::jsonb,true,null),
('{"text":"INSERT INTO"}'::jsonb,false,'Confuses CREATE TABLE with INSERT INTO'),
('{"text":"UPDATE"}'::jsonb,false,'Confuses CREATE TABLE with UPDATE'),
('{"text":"SELECT"}'::jsonb,false,'Confuses CREATE TABLE with SELECT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','easy','Which command adds a row?','INSERT adds rows and belongs to DML.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"INSERT"}'::jsonb,true,null),
('{"text":"ALTER"}'::jsonb,false,'Confuses INSERT with ALTER'),
('{"text":"DROP"}'::jsonb,false,'Confuses INSERT with DROP'),
('{"text":"GRANT"}'::jsonb,false,'Confuses INSERT with GRANT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','easy','Which command changes existing rows?','UPDATE modifies existing row values.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"UPDATE"}'::jsonb,true,null),
('{"text":"CREATE"}'::jsonb,false,'Confuses UPDATE with CREATE'),
('{"text":"REVOKE"}'::jsonb,false,'Confuses UPDATE with REVOKE'),
('{"text":"COMMIT"}'::jsonb,false,'Confuses UPDATE with COMMIT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','easy','Which command removes matching rows?','DELETE removes rows, optionally selected using WHERE.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"DELETE"}'::jsonb,true,null),
('{"text":"DROP TABLE"}'::jsonb,false,'Confuses DELETE with DROP TABLE'),
('{"text":"ALTER TABLE"}'::jsonb,false,'Confuses DELETE with ALTER TABLE'),
('{"text":"GRANT"}'::jsonb,false,'Confuses DELETE with GRANT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','easy','Which command removes a table definition?','DROP TABLE removes the table itself, not merely its rows.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"DROP TABLE"}'::jsonb,true,null),
('{"text":"DELETE"}'::jsonb,false,'Confuses DROP TABLE with DELETE'),
('{"text":"SELECT"}'::jsonb,false,'Confuses DROP TABLE with SELECT'),
('{"text":"ROLLBACK"}'::jsonb,false,'Confuses DROP TABLE with ROLLBACK')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','easy','Which command adds a column?','ALTER TABLE changes a table definition.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"ALTER TABLE"}'::jsonb,true,null),
('{"text":"INSERT"}'::jsonb,false,'Confuses ALTER TABLE with INSERT'),
('{"text":"UPDATE"}'::jsonb,false,'Confuses ALTER TABLE with UPDATE'),
('{"text":"COMMIT"}'::jsonb,false,'Confuses ALTER TABLE with COMMIT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','easy','Which command makes transaction changes permanent?','COMMIT successfully ends the transaction and persists its changes.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"COMMIT"}'::jsonb,true,null),
('{"text":"ROLLBACK"}'::jsonb,false,'Confuses COMMIT with ROLLBACK'),
('{"text":"SAVEPOINT"}'::jsonb,false,'Confuses COMMIT with SAVEPOINT'),
('{"text":"REVOKE"}'::jsonb,false,'Confuses COMMIT with REVOKE')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','easy','Which command undoes an uncommitted transaction?','ROLLBACK abandons changes in the current transaction.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"ROLLBACK"}'::jsonb,true,null),
('{"text":"COMMIT"}'::jsonb,false,'Confuses ROLLBACK with COMMIT'),
('{"text":"GRANT"}'::jsonb,false,'Confuses ROLLBACK with GRANT'),
('{"text":"SELECT"}'::jsonb,false,'Confuses ROLLBACK with SELECT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','easy','Which command marks a partial rollback point?','SAVEPOINT marks a point that ROLLBACK TO can return to.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"SAVEPOINT"}'::jsonb,true,null),
('{"text":"COMMIT"}'::jsonb,false,'Confuses SAVEPOINT with COMMIT'),
('{"text":"CREATE DATABASE"}'::jsonb,false,'Confuses SAVEPOINT with CREATE DATABASE'),
('{"text":"GRANT"}'::jsonb,false,'Confuses SAVEPOINT with GRANT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','easy','Which command gives a privilege?','GRANT assigns privileges to a role.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"GRANT"}'::jsonb,true,null),
('{"text":"REVOKE"}'::jsonb,false,'Confuses GRANT with REVOKE'),
('{"text":"INSERT"}'::jsonb,false,'Confuses GRANT with INSERT'),
('{"text":"SAVEPOINT"}'::jsonb,false,'Confuses GRANT with SAVEPOINT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','easy','Which command removes a granted privilege?','REVOKE removes a privilege grant.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"REVOKE"}'::jsonb,true,null),
('{"text":"GRANT"}'::jsonb,false,'Confuses REVOKE with GRANT'),
('{"text":"DROP COLUMN"}'::jsonb,false,'Confuses REVOKE with DROP COLUMN'),
('{"text":"DELETE"}'::jsonb,false,'Confuses REVOKE with DELETE')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','easy','Which command starts a transaction?','BEGIN opens a transaction block.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"BEGIN"}'::jsonb,true,null),
('{"text":"END TABLE"}'::jsonb,false,'Confuses BEGIN with END TABLE'),
('{"text":"GRANT"}'::jsonb,false,'Confuses BEGIN with GRANT'),
('{"text":"ALTER"}'::jsonb,false,'Confuses BEGIN with ALTER')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','easy','Which family contains CREATE and ALTER?','Data Definition Language describes commands that define database structures.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"DDL"}'::jsonb,true,null),
('{"text":"DML"}'::jsonb,false,'Confuses DDL with DML'),
('{"text":"TCL"}'::jsonb,false,'Confuses DDL with TCL'),
('{"text":"DCL"}'::jsonb,false,'Confuses DDL with DCL')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','easy','Which family contains COMMIT and ROLLBACK?','Transaction Control Language includes COMMIT and ROLLBACK.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"TCL"}'::jsonb,true,null),
('{"text":"DDL"}'::jsonb,false,'Confuses TCL with DDL'),
('{"text":"DML"}'::jsonb,false,'Confuses TCL with DML'),
('{"text":"DCL"}'::jsonb,false,'Confuses TCL with DCL')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','easy','Which family contains GRANT and REVOKE?','Data Control Language includes privilege management commands.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"DCL"}'::jsonb,true,null),
('{"text":"DDL"}'::jsonb,false,'Confuses DCL with DDL'),
('{"text":"DML"}'::jsonb,false,'Confuses DCL with DML'),
('{"text":"TCL"}'::jsonb,false,'Confuses DCL with TCL')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','At the gate: Which command creates a table?','CREATE TABLE defines a new relation and belongs to DDL.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"CREATE TABLE"}'::jsonb,true,null),
('{"text":"INSERT INTO"}'::jsonb,false,'Confuses CREATE TABLE with INSERT INTO'),
('{"text":"UPDATE"}'::jsonb,false,'Confuses CREATE TABLE with UPDATE'),
('{"text":"SELECT"}'::jsonb,false,'Confuses CREATE TABLE with SELECT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','At the gate: Which command adds a row?','INSERT adds rows and belongs to DML.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"INSERT"}'::jsonb,true,null),
('{"text":"ALTER"}'::jsonb,false,'Confuses INSERT with ALTER'),
('{"text":"DROP"}'::jsonb,false,'Confuses INSERT with DROP'),
('{"text":"GRANT"}'::jsonb,false,'Confuses INSERT with GRANT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','At the gate: Which command changes existing rows?','UPDATE modifies existing row values.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"UPDATE"}'::jsonb,true,null),
('{"text":"CREATE"}'::jsonb,false,'Confuses UPDATE with CREATE'),
('{"text":"REVOKE"}'::jsonb,false,'Confuses UPDATE with REVOKE'),
('{"text":"COMMIT"}'::jsonb,false,'Confuses UPDATE with COMMIT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','At the gate: Which command removes matching rows?','DELETE removes rows, optionally selected using WHERE.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"DELETE"}'::jsonb,true,null),
('{"text":"DROP TABLE"}'::jsonb,false,'Confuses DELETE with DROP TABLE'),
('{"text":"ALTER TABLE"}'::jsonb,false,'Confuses DELETE with ALTER TABLE'),
('{"text":"GRANT"}'::jsonb,false,'Confuses DELETE with GRANT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','At the gate: Which command removes a table definition?','DROP TABLE removes the table itself, not merely its rows.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"DROP TABLE"}'::jsonb,true,null),
('{"text":"DELETE"}'::jsonb,false,'Confuses DROP TABLE with DELETE'),
('{"text":"SELECT"}'::jsonb,false,'Confuses DROP TABLE with SELECT'),
('{"text":"ROLLBACK"}'::jsonb,false,'Confuses DROP TABLE with ROLLBACK')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','At the gate: Which command adds a column?','ALTER TABLE changes a table definition.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"ALTER TABLE"}'::jsonb,true,null),
('{"text":"INSERT"}'::jsonb,false,'Confuses ALTER TABLE with INSERT'),
('{"text":"UPDATE"}'::jsonb,false,'Confuses ALTER TABLE with UPDATE'),
('{"text":"COMMIT"}'::jsonb,false,'Confuses ALTER TABLE with COMMIT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','At the gate: Which command makes transaction changes permanent?','COMMIT successfully ends the transaction and persists its changes.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"COMMIT"}'::jsonb,true,null),
('{"text":"ROLLBACK"}'::jsonb,false,'Confuses COMMIT with ROLLBACK'),
('{"text":"SAVEPOINT"}'::jsonb,false,'Confuses COMMIT with SAVEPOINT'),
('{"text":"REVOKE"}'::jsonb,false,'Confuses COMMIT with REVOKE')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','At the gate: Which command undoes an uncommitted transaction?','ROLLBACK abandons changes in the current transaction.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"ROLLBACK"}'::jsonb,true,null),
('{"text":"COMMIT"}'::jsonb,false,'Confuses ROLLBACK with COMMIT'),
('{"text":"GRANT"}'::jsonb,false,'Confuses ROLLBACK with GRANT'),
('{"text":"SELECT"}'::jsonb,false,'Confuses ROLLBACK with SELECT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','At the gate: Which command marks a partial rollback point?','SAVEPOINT marks a point that ROLLBACK TO can return to.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"SAVEPOINT"}'::jsonb,true,null),
('{"text":"COMMIT"}'::jsonb,false,'Confuses SAVEPOINT with COMMIT'),
('{"text":"CREATE DATABASE"}'::jsonb,false,'Confuses SAVEPOINT with CREATE DATABASE'),
('{"text":"GRANT"}'::jsonb,false,'Confuses SAVEPOINT with GRANT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','At the gate: Which command gives a privilege?','GRANT assigns privileges to a role.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"GRANT"}'::jsonb,true,null),
('{"text":"REVOKE"}'::jsonb,false,'Confuses GRANT with REVOKE'),
('{"text":"INSERT"}'::jsonb,false,'Confuses GRANT with INSERT'),
('{"text":"SAVEPOINT"}'::jsonb,false,'Confuses GRANT with SAVEPOINT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','At the gate: Which command removes a granted privilege?','REVOKE removes a privilege grant.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"REVOKE"}'::jsonb,true,null),
('{"text":"GRANT"}'::jsonb,false,'Confuses REVOKE with GRANT'),
('{"text":"DROP COLUMN"}'::jsonb,false,'Confuses REVOKE with DROP COLUMN'),
('{"text":"DELETE"}'::jsonb,false,'Confuses REVOKE with DELETE')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','At the gate: Which command starts a transaction?','BEGIN opens a transaction block.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"BEGIN"}'::jsonb,true,null),
('{"text":"END TABLE"}'::jsonb,false,'Confuses BEGIN with END TABLE'),
('{"text":"GRANT"}'::jsonb,false,'Confuses BEGIN with GRANT'),
('{"text":"ALTER"}'::jsonb,false,'Confuses BEGIN with ALTER')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','At the gate: Which family contains CREATE and ALTER?','Data Definition Language describes commands that define database structures.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"DDL"}'::jsonb,true,null),
('{"text":"DML"}'::jsonb,false,'Confuses DDL with DML'),
('{"text":"TCL"}'::jsonb,false,'Confuses DDL with TCL'),
('{"text":"DCL"}'::jsonb,false,'Confuses DDL with DCL')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','At the gate: Which family contains COMMIT and ROLLBACK?','Transaction Control Language includes COMMIT and ROLLBACK.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"TCL"}'::jsonb,true,null),
('{"text":"DDL"}'::jsonb,false,'Confuses TCL with DDL'),
('{"text":"DML"}'::jsonb,false,'Confuses TCL with DML'),
('{"text":"DCL"}'::jsonb,false,'Confuses TCL with DCL')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','At the gate: Which family contains GRANT and REVOKE?','Data Control Language includes privilege management commands.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"DCL"}'::jsonb,true,null),
('{"text":"DDL"}'::jsonb,false,'Confuses DCL with DDL'),
('{"text":"DML"}'::jsonb,false,'Confuses DCL with DML'),
('{"text":"TCL"}'::jsonb,false,'Confuses DCL with TCL')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','Inside the vault: Which command creates a table?','CREATE TABLE defines a new relation and belongs to DDL.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"CREATE TABLE"}'::jsonb,true,null),
('{"text":"INSERT INTO"}'::jsonb,false,'Confuses CREATE TABLE with INSERT INTO'),
('{"text":"UPDATE"}'::jsonb,false,'Confuses CREATE TABLE with UPDATE'),
('{"text":"SELECT"}'::jsonb,false,'Confuses CREATE TABLE with SELECT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','Inside the vault: Which command adds a row?','INSERT adds rows and belongs to DML.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"INSERT"}'::jsonb,true,null),
('{"text":"ALTER"}'::jsonb,false,'Confuses INSERT with ALTER'),
('{"text":"DROP"}'::jsonb,false,'Confuses INSERT with DROP'),
('{"text":"GRANT"}'::jsonb,false,'Confuses INSERT with GRANT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','Inside the vault: Which command changes existing rows?','UPDATE modifies existing row values.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"UPDATE"}'::jsonb,true,null),
('{"text":"CREATE"}'::jsonb,false,'Confuses UPDATE with CREATE'),
('{"text":"REVOKE"}'::jsonb,false,'Confuses UPDATE with REVOKE'),
('{"text":"COMMIT"}'::jsonb,false,'Confuses UPDATE with COMMIT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','Inside the vault: Which command removes matching rows?','DELETE removes rows, optionally selected using WHERE.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"DELETE"}'::jsonb,true,null),
('{"text":"DROP TABLE"}'::jsonb,false,'Confuses DELETE with DROP TABLE'),
('{"text":"ALTER TABLE"}'::jsonb,false,'Confuses DELETE with ALTER TABLE'),
('{"text":"GRANT"}'::jsonb,false,'Confuses DELETE with GRANT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','medium','Inside the vault: Which command removes a table definition?','DROP TABLE removes the table itself, not merely its rows.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"DROP TABLE"}'::jsonb,true,null),
('{"text":"DELETE"}'::jsonb,false,'Confuses DROP TABLE with DELETE'),
('{"text":"SELECT"}'::jsonb,false,'Confuses DROP TABLE with SELECT'),
('{"text":"ROLLBACK"}'::jsonb,false,'Confuses DROP TABLE with ROLLBACK')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','hard','Inside the vault: Which command adds a column?','ALTER TABLE changes a table definition.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"ALTER TABLE"}'::jsonb,true,null),
('{"text":"INSERT"}'::jsonb,false,'Confuses ALTER TABLE with INSERT'),
('{"text":"UPDATE"}'::jsonb,false,'Confuses ALTER TABLE with UPDATE'),
('{"text":"COMMIT"}'::jsonb,false,'Confuses ALTER TABLE with COMMIT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','hard','Inside the vault: Which command makes transaction changes permanent?','COMMIT successfully ends the transaction and persists its changes.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"COMMIT"}'::jsonb,true,null),
('{"text":"ROLLBACK"}'::jsonb,false,'Confuses COMMIT with ROLLBACK'),
('{"text":"SAVEPOINT"}'::jsonb,false,'Confuses COMMIT with SAVEPOINT'),
('{"text":"REVOKE"}'::jsonb,false,'Confuses COMMIT with REVOKE')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','hard','Inside the vault: Which command undoes an uncommitted transaction?','ROLLBACK abandons changes in the current transaction.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"ROLLBACK"}'::jsonb,true,null),
('{"text":"COMMIT"}'::jsonb,false,'Confuses ROLLBACK with COMMIT'),
('{"text":"GRANT"}'::jsonb,false,'Confuses ROLLBACK with GRANT'),
('{"text":"SELECT"}'::jsonb,false,'Confuses ROLLBACK with SELECT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','hard','Inside the vault: Which command marks a partial rollback point?','SAVEPOINT marks a point that ROLLBACK TO can return to.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"SAVEPOINT"}'::jsonb,true,null),
('{"text":"COMMIT"}'::jsonb,false,'Confuses SAVEPOINT with COMMIT'),
('{"text":"CREATE DATABASE"}'::jsonb,false,'Confuses SAVEPOINT with CREATE DATABASE'),
('{"text":"GRANT"}'::jsonb,false,'Confuses SAVEPOINT with GRANT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','hard','Inside the vault: Which command gives a privilege?','GRANT assigns privileges to a role.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"GRANT"}'::jsonb,true,null),
('{"text":"REVOKE"}'::jsonb,false,'Confuses GRANT with REVOKE'),
('{"text":"INSERT"}'::jsonb,false,'Confuses GRANT with INSERT'),
('{"text":"SAVEPOINT"}'::jsonb,false,'Confuses GRANT with SAVEPOINT')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','hard','Inside the vault: Which command removes a granted privilege?','REVOKE removes a privilege grant.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"REVOKE"}'::jsonb,true,null),
('{"text":"GRANT"}'::jsonb,false,'Confuses REVOKE with GRANT'),
('{"text":"DROP COLUMN"}'::jsonb,false,'Confuses REVOKE with DROP COLUMN'),
('{"text":"DELETE"}'::jsonb,false,'Confuses REVOKE with DELETE')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','hard','Inside the vault: Which command starts a transaction?','BEGIN opens a transaction block.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"BEGIN"}'::jsonb,true,null),
('{"text":"END TABLE"}'::jsonb,false,'Confuses BEGIN with END TABLE'),
('{"text":"GRANT"}'::jsonb,false,'Confuses BEGIN with GRANT'),
('{"text":"ALTER"}'::jsonb,false,'Confuses BEGIN with ALTER')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','hard','Inside the vault: Which family contains CREATE and ALTER?','Data Definition Language describes commands that define database structures.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"DDL"}'::jsonb,true,null),
('{"text":"DML"}'::jsonb,false,'Confuses DDL with DML'),
('{"text":"TCL"}'::jsonb,false,'Confuses DDL with TCL'),
('{"text":"DCL"}'::jsonb,false,'Confuses DDL with DCL')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','hard','Inside the vault: Which family contains COMMIT and ROLLBACK?','Transaction Control Language includes COMMIT and ROLLBACK.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"TCL"}'::jsonb,true,null),
('{"text":"DDL"}'::jsonb,false,'Confuses TCL with DDL'),
('{"text":"DML"}'::jsonb,false,'Confuses TCL with DML'),
('{"text":"DCL"}'::jsonb,false,'Confuses TCL with DCL')) v(body,correct,misconception);
with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(2,'concept','hard','Inside the vault: Which family contains GRANT and REVOKE?','Data Control Language includes privilege management commands.') returning id)
insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values
('{"text":"DCL"}'::jsonb,true,null),
('{"text":"DDL"}'::jsonb,false,'Confuses DCL with DDL'),
('{"text":"DML"}'::jsonb,false,'Confuses DCL with DML'),
('{"text":"TCL"}'::jsonb,false,'Confuses DCL with TCL')) v(body,correct,misconception);
commit;
