// Generates supabase/seed.sql from the DBMS 2026 topic tree.
// Each round maps to a lecture (L1-L8, L10) and its questions cover that
// module's leaf topics. Tuples are [difficulty, stem, correct, d1, d2, d3,
// explanation]; the first option is the correct one. Content is a reviewable
// starter pool, not a finished, class-graded bank.
import { writeFileSync } from 'node:fs';

const E = 'easy',
  M = 'medium',
  H = 'hard';

const rounds = [
  {
    id: 1,
    lecture: 'L1',
    theme: 'vault-of-keys',
    title: 'The Vault of Keys',
    // Module 1: keys, constraints, schema, datatypes. Built out for a 30-draw
    // (>=10 easy, >=14 medium, >=6 hard).
    questions: [
      [
        E,
        'Which key uniquely identifies every row in a table?',
        'Primary key',
        'Foreign key',
        'Index',
        'Sort key',
        'A primary key uniquely identifies each row and can never be NULL.',
      ],
      [
        E,
        'Which key references the primary key of another table?',
        'Foreign key',
        'Candidate key',
        'Super key',
        'Primary key',
        'A foreign key points at a key in another (or the same) table.',
      ],
      [
        E,
        'Which constraint forbids NULL values in a column?',
        'NOT NULL',
        'UNIQUE',
        'DEFAULT',
        'CHECK',
        'NOT NULL rejects rows with a NULL in that column.',
      ],
      [
        E,
        'Which constraint rejects duplicate values in a column?',
        'UNIQUE',
        'NOT NULL',
        'DEFAULT',
        'INDEX',
        'UNIQUE forbids duplicate non-NULL values.',
      ],
      [
        E,
        'What does a schema describe?',
        'The structure of the database',
        'The current rows',
        'A single query result',
        'The backup file',
        'A schema defines tables, columns, types and constraints.',
      ],
      [
        E,
        'In the ER view, a customer is an example of a(n)…',
        'Entity',
        'Attribute',
        'Relationship',
        'Constraint',
        'An entity is a thing we store data about; its columns are attributes.',
      ],
      [
        E,
        "A person's email stored in a table is a(n)…",
        'Attribute',
        'Entity',
        'Relationship',
        'Tuple',
        'An attribute is a property (column) of an entity.',
      ],
      [
        E,
        'Which data type best stores a whole number?',
        'INTEGER',
        'VARCHAR',
        'BOOLEAN',
        'DATE',
        'INTEGER stores whole numbers.',
      ],
      [
        E,
        'Which data type best stores a true/false flag?',
        'BOOLEAN',
        'INTEGER',
        'TEXT',
        'NUMERIC',
        'BOOLEAN stores true or false.',
      ],
      [
        E,
        'Can a primary key column contain NULL?',
        'No, never',
        'Yes, always',
        'Only once',
        'Only for text',
        'A primary key can never be NULL.',
      ],
      [
        M,
        'A candidate key is best described as…',
        'A minimal super key',
        'Any super key',
        'A foreign key',
        'A unique column that allows NULL',
        'A candidate key is a super key with no removable attribute.',
      ],
      [
        M,
        'A super key is…',
        'Any column set that uniquely identifies a row',
        'Always a single column',
        'The primary key only',
        'A key that may be NULL',
        'A super key identifies rows but may carry extra columns.',
      ],
      [
        M,
        'Referential integrity guarantees that…',
        'A foreign key value matches an existing referenced key',
        'No column is NULL',
        'Every table has a primary key',
        'Rows are unique',
        'Referential integrity keeps foreign keys pointing at real rows.',
      ],
      [
        M,
        'Entity integrity guarantees that…',
        'No part of a primary key is NULL',
        'Foreign keys always match',
        'Columns have defaults',
        'Tables are normalized',
        'Entity integrity requires a complete, non-NULL primary key.',
      ],
      [
        M,
        'A key made of two columns together is a…',
        'Composite key',
        'Foreign key',
        'Domain key',
        'Surrogate key',
        'A composite (compound) key spans more than one column.',
      ],
      [
        M,
        'Which is TRUE of UNIQUE vs PRIMARY KEY?',
        'A table has many UNIQUE constraints but one primary key',
        'Both allow many NULLs',
        'PRIMARY KEY allows NULL',
        'UNIQUE forbids more than one row',
        'A table has at most one primary key but several UNIQUE constraints.',
      ],
      [
        M,
        'A domain constraint restricts…',
        'The set of valid values for a column',
        'The number of rows',
        'Which user can read',
        'The join order',
        'Domain constraints (type/CHECK) bound a column’s allowed values.',
      ],
      [
        M,
        'Which is the best natural primary key for a country table?',
        'ISO country code',
        'Country name',
        'Population',
        'Capital city',
        'A short, stable, unique code is a good natural key; names change.',
      ],
      [
        M,
        'A foreign key may be NULL when…',
        'The relationship is optional',
        'Never',
        'Only for composite keys',
        'Only within one table',
        'A nullable foreign key models an optional relationship.',
      ],
      [
        M,
        'Deleting a row still referenced by a foreign key (no cascade) will…',
        'Be blocked / fail',
        'Silently delete children',
        'Set the parent to NULL',
        'Duplicate the row',
        'Referential integrity blocks the delete unless ON DELETE is set.',
      ],
      [
        M,
        'Which best distinguishes candidate key from primary key?',
        'The primary key is the chosen candidate key',
        'They are unrelated',
        'Candidate keys allow NULL',
        'A table has many primary keys',
        'One candidate key is selected to be the primary key.',
      ],
      [
        M,
        'VARCHAR(10) compared with CHAR(10): VARCHAR…',
        'Stores variable length up to 10',
        'Always uses 10 characters',
        'Rejects short strings',
        'Stores numbers',
        'VARCHAR stores only the characters supplied, up to the limit.',
      ],
      [
        M,
        'Which type suits money to avoid rounding errors?',
        'NUMERIC / DECIMAL',
        'FLOAT',
        'REAL',
        'INTEGER',
        'NUMERIC/DECIMAL is exact; floating types can round.',
      ],
      [
        M,
        'An attribute that splits into parts (e.g. full name) is…',
        'Composite attribute',
        'Derived attribute',
        'Key attribute',
        'Multivalued attribute',
        'A composite attribute is built from smaller sub-attributes.',
      ],
      [
        H,
        'UNIQUE(email) with email nullable: how many rows may have email NULL?',
        'Many',
        'Exactly one',
        'Zero',
        'Only if it is the PK',
        'UNIQUE treats NULLs as distinct, so multiple NULLs are allowed.',
      ],
      [
        H,
        'A candidate key must satisfy…',
        'Uniqueness and irreducibility',
        'Uniqueness only',
        'Being the first column',
        'Being NOT NULL text',
        'A candidate key is unique and minimal (irreducible).',
      ],
      [
        H,
        'A self-referencing foreign key models…',
        'A hierarchy within one table (e.g. manager_id)',
        'A many-to-many across tables',
        'A composite key',
        'A domain constraint',
        'A foreign key to the same table models hierarchies.',
      ],
      [
        H,
        'A surrogate key is preferred over a natural key mainly when…',
        'Natural identifiers can change',
        'You want slower joins',
        'Storage must grow',
        'NULLs are required',
        'Surrogate keys stay stable even if business values change.',
      ],
      [
        H,
        'Which violates entity integrity?',
        'Part of a composite primary key is NULL',
        'A NULL in a non-key column',
        'A duplicate value in a non-unique column',
        'A cascade delete',
        'Any NULL in a primary key breaks entity integrity.',
      ],
      [
        H,
        'You need at most one profile per user. Which enforces it?',
        'UNIQUE (or PK) on profile.user_id',
        'NOT NULL on user_id',
        'A CHECK on age',
        'An index on name',
        'A UNIQUE/PK on the foreign key enforces one-to-one.',
      ],
      [
        E,
        'Which data type stores text of variable length?',
        'VARCHAR',
        'INTEGER',
        'BOOLEAN',
        'DATE',
        'VARCHAR stores variable-length text.',
      ],
      [
        E,
        "A table's columns are also called its…",
        'Attributes',
        'Rows',
        'Tuples',
        'Keys',
        'Columns are attributes; rows are tuples.',
      ],
      [
        E,
        'Which key is chosen to be the main identifier of a table?',
        'Primary key',
        'Foreign key',
        'Super key',
        'Composite key',
        'The primary key is the chosen candidate key.',
      ],
      [
        E,
        'Which constraint links a column to another table?',
        'FOREIGN KEY',
        'UNIQUE',
        'NOT NULL',
        'CHECK',
        'A foreign key relates two tables.',
      ],
      [
        E,
        'A DATE column stores…',
        'A calendar date',
        'A number',
        'A boolean',
        'Free text',
        'DATE stores a calendar date.',
      ],
      [
        M,
        'Which enforces that age is between 0 and 150?',
        'CHECK (age between 0 and 150)',
        'NOT NULL',
        'UNIQUE',
        'DEFAULT 0',
        'A CHECK constraint restricts allowed values.',
      ],
      [
        M,
        'A DEFAULT constraint provides…',
        'A value used when none is given',
        'A unique value',
        'A foreign key',
        'A primary key',
        'DEFAULT fills a column when no value is supplied.',
      ],
      [
        M,
        'Which is TRUE of a composite primary key?',
        'All its columns together must be unique and non-NULL',
        'Each column alone is unique',
        'It allows NULLs',
        'Only one column matters',
        'The combination must be unique and fully non-NULL.',
      ],
      [
        M,
        'A one-to-many relationship stores the foreign key on…',
        "The 'many' side",
        "The 'one' side",
        'A new table always',
        'Neither side',
        'The many side references the one side.',
      ],
      [
        M,
        'Which models many students enrolling in many courses?',
        'A junction table with two foreign keys',
        'One foreign key',
        'A CHECK constraint',
        'A unique index',
        'Many-to-many needs a bridge table.',
      ],
      [
        M,
        'NUMERIC(5,2) can store at most…',
        '999.99',
        '99999',
        'only integers',
        'any real number',
        'Five total digits with two after the decimal point.',
      ],
      [
        H,
        'Adding a NOT NULL column to a table that already has rows requires…',
        'A default value (or filling the column)',
        'Nothing extra',
        'Dropping the table',
        'A new primary key',
        'Existing rows need a value for the new NOT NULL column.',
      ],
      [
        H,
        'ON DELETE CASCADE on a foreign key means…',
        'Deleting the parent deletes matching children',
        'The delete is blocked',
        'The child is set to NULL',
        'Nothing happens',
        'CASCADE propagates the delete to child rows.',
      ],
      [
        H,
        'Which allows a missing email yet forbids two equal emails?',
        'UNIQUE on a nullable email',
        'PRIMARY KEY on email',
        'NOT NULL on email',
        'CHECK on email',
        'UNIQUE permits NULLs but forbids duplicate non-NULLs.',
      ],
      [
        H,
        'A candidate key not chosen as the primary key is called…',
        'An alternate key',
        'A foreign key',
        'A super key',
        'A partial key',
        'Unchosen candidate keys are alternate keys.',
      ],
    ],
  },
  {
    id: 2,
    lecture: 'L2',
    theme: 'guild-city',
    title: 'Guild City',
    // Module 2: DDL / DML / TCL / DCL.
    questions: [
      [
        E,
        'CREATE TABLE belongs to which SQL family?',
        'DDL',
        'DML',
        'TCL',
        'DCL',
        'DDL defines structures: CREATE, ALTER, DROP, TRUNCATE.',
      ],
      [
        E,
        'INSERT, UPDATE and DELETE belong to which family?',
        'DML',
        'DDL',
        'TCL',
        'DCL',
        'DML manipulates the data inside rows.',
      ],
      [
        E,
        'COMMIT and ROLLBACK belong to which family?',
        'TCL',
        'DDL',
        'DML',
        'DCL',
        'TCL controls transactions.',
      ],
      [
        E,
        'GRANT and REVOKE belong to which family?',
        'DCL',
        'DDL',
        'DML',
        'TCL',
        'DCL controls privileges.',
      ],
      [
        E,
        'Which command removes a table definition and all its data?',
        'DROP TABLE',
        'DELETE',
        'TRUNCATE',
        'ALTER',
        'DROP removes the whole table object.',
      ],
      [
        E,
        'Which command adds new rows?',
        'INSERT',
        'UPDATE',
        'ALTER',
        'SELECT',
        'INSERT adds rows to a table.',
      ],
      [
        E,
        'Which command changes existing rows?',
        'UPDATE',
        'INSERT',
        'ALTER',
        'CREATE',
        'UPDATE modifies existing rows.',
      ],
      [
        E,
        'Which command permanently saves the current transaction?',
        'COMMIT',
        'ROLLBACK',
        'SAVEPOINT',
        'GRANT',
        'COMMIT persists the transaction’s changes.',
      ],
      [
        E,
        'Which command grants a privilege to a user?',
        'GRANT',
        'REVOKE',
        'COMMIT',
        'ALTER',
        'GRANT assigns privileges to a role.',
      ],
      [
        M,
        'Which quickly removes all rows but keeps the table structure?',
        'TRUNCATE',
        'DROP',
        'ALTER',
        'CREATE',
        'TRUNCATE empties a table fast; the structure remains.',
      ],
      [
        M,
        'Which adds a new column to an existing table?',
        'ALTER TABLE … ADD COLUMN',
        'UPDATE',
        'CREATE COLUMN',
        'INSERT COLUMN',
        'ALTER changes an existing table’s structure.',
      ],
      [
        M,
        'DELETE vs TRUNCATE: which can use a WHERE clause?',
        'DELETE',
        'TRUNCATE',
        'Both equally',
        'Neither',
        'DELETE can filter rows; TRUNCATE removes them all.',
      ],
      [
        M,
        'Which undoes changes made since the last commit?',
        'ROLLBACK',
        'COMMIT',
        'SAVEPOINT',
        'REVOKE',
        'ROLLBACK discards the current transaction’s changes.',
      ],
      [
        M,
        'SAVEPOINT is used to…',
        'Mark a point to roll back to partially',
        'End a transaction',
        'Grant access',
        'Drop a table',
        'ROLLBACK TO SAVEPOINT undoes part of a transaction.',
      ],
      [
        M,
        'Which removes a previously granted privilege?',
        'REVOKE',
        'GRANT',
        'DROP',
        'DENY',
        'REVOKE withdraws a granted privilege.',
      ],
      [
        H,
        'In PostgreSQL, is TRUNCATE inside a transaction reversible?',
        'Yes, it can be rolled back',
        'No, never',
        'Only with SAVEPOINT',
        'Only on empty tables',
        'In PostgreSQL TRUNCATE is transactional and can be rolled back.',
      ],
      [
        E,
        'Which command creates a new table?',
        'CREATE TABLE',
        'ALTER TABLE',
        'INSERT',
        'MAKE TABLE',
        'CREATE TABLE defines a new table.',
      ],
      [
        E,
        'Which command retrieves rows from a table?',
        'SELECT',
        'INSERT',
        'UPDATE',
        'GRANT',
        'SELECT reads rows.',
      ],
      [
        E,
        'SELECT is used to…',
        'Query data',
        'Define structure',
        'Control transactions',
        'Grant access',
        'SELECT reads data from tables.',
      ],
      [
        E,
        'Which command starts a transaction block?',
        'BEGIN',
        'COMMIT',
        'GRANT',
        'ALTER',
        'BEGIN opens a transaction.',
      ],
      [
        E,
        'Which removes specific rows using a condition?',
        'DELETE … WHERE',
        'DROP',
        'TRUNCATE',
        'ALTER',
        'DELETE with WHERE removes matching rows.',
      ],
      [
        E,
        'Which command changes a table’s structure?',
        'ALTER TABLE',
        'UPDATE',
        'RENAME ROW',
        'CREATE',
        'ALTER modifies an existing table.',
      ],
      [
        M,
        'DROP TABLE differs from DELETE because DROP…',
        'Removes the table itself',
        'Removes rows only',
        'Needs a WHERE clause',
        'Only reorders rows',
        'DROP removes the whole table object.',
      ],
      [
        M,
        'ALTER TABLE … DROP COLUMN does what?',
        'Removes a column and its data',
        'Deletes rows',
        'Renames the table',
        'Adds a column',
        'DROP COLUMN removes the column.',
      ],
      [
        M,
        'INSERT INTO t VALUES (…) adds…',
        'A new row',
        'A new column',
        'A constraint',
        'A table',
        'INSERT adds rows.',
      ],
      [
        M,
        'UPDATE without a WHERE clause…',
        'Changes every row',
        'Changes nothing',
        'Raises an error',
        'Deletes rows',
        'With no WHERE, all rows are updated.',
      ],
      [
        M,
        'COMMIT does what to changes made since BEGIN?',
        'Makes them permanent',
        'Discards them',
        'Pauses them',
        'Locks the table forever',
        'COMMIT persists the transaction.',
      ],
      [
        M,
        'ROLLBACK TO SAVEPOINT s undoes…',
        'Changes made after s',
        'The whole transaction',
        'Nothing',
        'Already-committed changes',
        'It rewinds to the savepoint.',
      ],
      [
        M,
        'GRANT SELECT ON t TO alice lets alice…',
        'Read table t',
        "Change t's structure",
        'Drop t',
        'Grant to others',
        'GRANT SELECT permits reading.',
      ],
      [
        M,
        'REVOKE SELECT ON t FROM alice…',
        "Removes alice's read access",
        'Deletes alice',
        'Drops t',
        'Adds access',
        'REVOKE withdraws the privilege.',
      ],
      [
        M,
        'Which family does ALTER belong to?',
        'DDL',
        'DML',
        'TCL',
        'DCL',
        'ALTER defines structure (DDL).',
      ],
      [
        M,
        'Which family does UPDATE belong to?',
        'DML',
        'DDL',
        'TCL',
        'DCL',
        'UPDATE manipulates data (DML).',
      ],
      [
        M,
        'Which family does SAVEPOINT belong to?',
        'TCL',
        'DDL',
        'DML',
        'DCL',
        'SAVEPOINT controls transactions (TCL).',
      ],
      [
        M,
        'Which command changes a column’s data type?',
        'ALTER TABLE … ALTER COLUMN … TYPE',
        'UPDATE',
        'MODIFY ROW',
        'CAST TABLE',
        'ALTER COLUMN changes the type.',
      ],
      [
        H,
        'In many databases, a DDL statement causes…',
        'An implicit commit of the current transaction',
        'An automatic rollback',
        'Nothing to the transaction',
        'A new savepoint',
        'DDL often auto-commits the transaction.',
      ],
      [
        H,
        'GRANT … WITH GRANT OPTION lets the grantee…',
        'Pass the privilege on to others',
        'Only read',
        'Drop the table',
        'Bypass all checks',
        'GRANT OPTION allows re-granting.',
      ],
      [
        H,
        'A key difference of TRUNCATE from DELETE is that TRUNCATE…',
        'Resets identity and skips per-row triggers',
        'Supports WHERE',
        'Is always row-by-row',
        'Cannot be rolled back in PostgreSQL',
        'TRUNCATE is a bulk, sequence-resetting operation.',
      ],
      [
        H,
        'After ROLLBACK, changes since the last COMMIT are…',
        'Undone',
        'Kept',
        'Committed',
        'Partially kept',
        'ROLLBACK discards them.',
      ],
      [
        H,
        'BEGIN; UPDATE pay=100; SAVEPOINT s; UPDATE pay=200; ROLLBACK TO s; COMMIT. Final pay?',
        '100',
        '200',
        'unchanged',
        'NULL',
        'Rolling back to s discards the 200 update, keeping 100.',
      ],
      [
        H,
        'REVOKE … CASCADE also removes privileges that…',
        'Were granted onward by the revokee',
        'The owner holds',
        'Are unrelated',
        'Belong to the table itself',
        'CASCADE revokes downstream grants.',
      ],
      [
        H,
        'Which is NOT reversible by ROLLBACK in most systems?',
        'A committed transaction',
        'An uncommitted UPDATE',
        'An uncommitted DELETE',
        'A savepoint',
        'Once committed, changes are permanent.',
      ],
      [
        H,
        'CREATE OR REPLACE VIEW differs from CREATE VIEW by…',
        'Redefining an existing view without dropping it',
        'Creating a table',
        'Deleting rows',
        'Granting access',
        'OR REPLACE updates the definition in place.',
      ],
      [
        H,
        'DELETE FROM t; with no WHERE, inside a transaction, can be undone by…',
        'ROLLBACK',
        'Nothing',
        'TRUNCATE',
        'COMMIT',
        'Uncommitted deletes are rolled back.',
      ],
      [
        H,
        'Which statement can filter which rows it removes?',
        'DELETE',
        'TRUNCATE',
        'DROP TABLE',
        'CREATE',
        'Only DELETE takes a WHERE clause.',
      ],
    ],
  },
  {
    id: 3,
    lecture: 'L3',
    theme: 'cipher-lock',
    title: 'The Cipher Lock',
    // Module 3: SELECT, DISTINCT, WHERE, IN, LIKE, EXISTS, wildcards, logic, LIMIT/OFFSET.
    questions: [
      [
        E,
        'Which clause chooses which columns to return?',
        'SELECT',
        'WHERE',
        'FROM',
        'GROUP BY',
        'SELECT lists the output columns.',
      ],
      [
        E,
        'Which removes duplicate rows from the result?',
        'DISTINCT',
        'UNIQUE',
        'GROUP',
        'LIMIT',
        'DISTINCT collapses duplicate result rows.',
      ],
      [
        E,
        'Which clause limits the result to the first 5 rows?',
        'LIMIT 5',
        'TOP 5',
        'ROWS 5',
        'FETCH',
        'LIMIT restricts the number of returned rows.',
      ],
      [
        E,
        'AND has higher precedence than OR, so A OR B AND C means…',
        'A OR (B AND C)',
        '(A OR B) AND C',
        'A AND (B OR C)',
        'left to right',
        'AND binds tighter than OR.',
      ],
      [
        M,
        'WHERE age IN (18, 21) is equivalent to…',
        'age = 18 OR age = 21',
        'age = 18 AND age = 21',
        'age BETWEEN 18 AND 21',
        'age <> 18',
        'IN matches any value in the list.',
      ],
      [
        M,
        'Which keeps 8-letter names starting with S and ending with n?',
        "name LIKE 'S______n'",
        "name LIKE 'S%n'",
        "name LIKE 'S_n'",
        "name LIKE '%S%n%'",
        'Each _ matches exactly one character; six of them fix the length at 8.',
      ],
      [
        M,
        'The % wildcard in LIKE matches…',
        'Any sequence of characters',
        'Exactly one character',
        'Only digits',
        'Nothing',
        '% matches zero or more characters; _ matches exactly one.',
      ],
      [
        M,
        'Which returns rows for which a matching order exists?',
        'WHERE EXISTS (subquery)',
        'WHERE IN only',
        'WHERE LIKE',
        'HAVING EXISTS',
        'EXISTS is true when the subquery returns at least one row.',
      ],
      [
        M,
        'OFFSET 10 LIMIT 5 returns…',
        'Rows 11–15',
        'Rows 1–5',
        'Rows 10–15',
        'Rows 6–10',
        'OFFSET skips rows before LIMIT takes the next ones.',
      ],
      [
        H,
        'NOT IN with a NULL in the list can…',
        'Return no rows unexpectedly',
        'Ignore the NULL',
        'Always error',
        'Behave like IN',
        'A NULL makes the comparison UNKNOWN, dropping rows.',
      ],
      [
        H,
        'Which finds emails containing a literal underscore?',
        "email LIKE '%\\_%' ESCAPE '\\'",
        "email LIKE '%_%'",
        "email LIKE '%__%'",
        "email = '_'",
        'Underscore is a wildcard, so it must be escaped to match literally.',
      ],
    ],
  },
  {
    id: 4,
    lecture: 'L4',
    theme: 'alchemists-workshop',
    title: 'The Alchemist’s Workshop',
    // Module 4: numeric, date, string, NULL and aggregate functions.
    questions: [
      [
        E,
        'ROUND(2.567, 1) returns…',
        '2.6',
        '2.5',
        '2.57',
        '3',
        'ROUND(x, 1) rounds to one decimal place.',
      ],
      [
        E,
        'ABS(-7) returns…',
        '7',
        '-7',
        '0',
        '1',
        'ABS returns the magnitude.',
      ],
      [
        E,
        "UPPER('sql') returns…",
        "'SQL'",
        "'sql'",
        "'Sql'",
        '3',
        'UPPER upper-cases text.',
      ],
      [
        E,
        'Which returns the current date and time?',
        'NOW()',
        'TODAY()',
        'CLOCK()',
        'DATE()',
        'NOW() returns the current timestamp.',
      ],
      [
        M,
        'FLOOR(2.9) returns…',
        '2',
        '3',
        '2.9',
        '-2',
        'FLOOR gives the largest integer <= x.',
      ],
      [
        M,
        'CEIL(2.1) returns…',
        '3',
        '2',
        '2.1',
        '-3',
        'CEIL gives the smallest integer >= x.',
      ],
      [
        M,
        'TRUNC(2.99) returns…',
        '2',
        '3',
        '2.9',
        '0',
        'TRUNC drops the fractional part toward zero.',
      ],
      [
        M,
        'POWER(2, 3) returns…',
        '8',
        '6',
        '9',
        '5',
        'POWER(x, y) is x raised to the power y.',
      ],
      [
        M,
        'EXTRACT(YEAR FROM d) returns…',
        'The year part of d',
        'The whole date',
        'The month',
        'A text label',
        'EXTRACT pulls a single field from a date/time.',
      ],
      [
        M,
        "DATE_TRUNC('month', ts) returns…",
        'The timestamp at the start of its month',
        'The month number',
        'The month name',
        'The day',
        'DATE_TRUNC zeroes the finer fields.',
      ],
      [
        M,
        "TO_CHAR(now(), 'YYYY-MM-DD') returns…",
        'A formatted date string',
        'A number',
        'An interval',
        'The year only',
        'TO_CHAR formats a value as text.',
      ],
      [
        M,
        "LENGTH('data') returns…",
        '4',
        '5',
        "'data'",
        '1',
        'LENGTH counts the characters.',
      ],
      [
        M,
        "'a' || 'b' evaluates to…",
        "'ab'",
        "'a b'",
        "'ba'",
        '2',
        'The || operator concatenates strings (like CONCAT).',
      ],
      [
        M,
        "SUBSTRING('database', 1, 4) returns…",
        "'data'",
        "'base'",
        "'atab'",
        "'databas'",
        'SUBSTRING(s, start, len) takes len characters from start.',
      ],
      [
        M,
        "TRIM('  hi  ') returns…",
        "'hi'",
        "'  hi  '",
        "'hi  '",
        "'  hi'",
        'TRIM removes leading and trailing spaces.',
      ],
      [
        M,
        "COALESCE(NULL, NULL, 'x') returns…",
        "'x'",
        'NULL',
        "''",
        'the first NULL',
        'COALESCE returns the first non-NULL argument.',
      ],
      [
        M,
        'NULLIF(5, 5) returns…',
        'NULL',
        '5',
        '0',
        'true',
        'NULLIF returns NULL when its two arguments are equal.',
      ],
      [
        H,
        'COUNT(col) compared with COUNT(*): COUNT(col)…',
        'Ignores NULLs in col',
        'Counts NULLs too',
        'Errors on NULL',
        'Always equals COUNT(*)',
        'COUNT(column) skips NULLs; COUNT(*) counts all rows.',
      ],
    ],
  },
  {
    id: 5,
    lecture: 'L5',
    theme: 'card-table',
    title: 'The Card Table',
    // Module 5: GROUP BY, HAVING, CASE.
    questions: [
      [
        E,
        'GROUP BY is used to…',
        'Collapse rows into groups for aggregation',
        'Sort rows',
        'Filter rows',
        'Join tables',
        'GROUP BY forms the groups an aggregate summarizes.',
      ],
      [
        E,
        'Can you use COUNT(*) in a WHERE clause?',
        'No, use HAVING',
        'Yes',
        'Only with GROUP BY',
        'Only with DISTINCT',
        'Aggregates are not allowed in WHERE; use HAVING.',
      ],
      [
        M,
        'Which clause filters groups after aggregation?',
        'HAVING',
        'WHERE',
        'ON',
        'LIMIT',
        'HAVING filters aggregated groups; WHERE filters rows first.',
      ],
      [
        M,
        'WHERE is applied…',
        'Before grouping and aggregation',
        'After grouping',
        'Only to aggregates',
        'Never with GROUP BY',
        'WHERE filters input rows; HAVING filters the groups.',
      ],
      [
        M,
        'SELECT dept, COUNT(*) … requires…',
        'GROUP BY dept',
        'ORDER BY dept',
        'WHERE dept',
        'nothing extra',
        'A non-aggregated selected column must appear in GROUP BY.',
      ],
      [
        M,
        'Grouping by (dept, city) makes one group per…',
        'Unique dept + city combination',
        'dept only',
        'city only',
        'row',
        'Multi-column grouping keys on the combination.',
      ],
      [
        M,
        'COUNT(*) with GROUP BY returns…',
        'A row count per group',
        'The total row count',
        'Distinct values',
        'The NULL count',
        'The aggregate is computed within each group.',
      ],
      [
        M,
        'Which returns values dealt more than once?',
        'GROUP BY val HAVING COUNT(*) > 1',
        'WHERE COUNT(*) > 1',
        'GROUP BY val WHERE COUNT(*) > 1',
        'DISTINCT val',
        'Counting per value and filtering groups needs HAVING.',
      ],
      [
        M,
        "CASE WHEN score >= 50 THEN 'pass' ELSE 'fail' END produces…",
        'A value per row chosen by a condition',
        'A group',
        'An aggregate',
        'A join',
        'CASE returns a value selected by its conditions.',
      ],
      [
        H,
        'SELECT dept, name, COUNT(*) GROUP BY dept errors because…',
        'name is neither grouped nor aggregated',
        'COUNT needs a column',
        'dept must be aggregated',
        'there are too many columns',
        'Every selected non-aggregate column must be in GROUP BY.',
      ],
      [
        H,
        'SUM(CASE WHEN paid THEN 1 ELSE 0 END) computes…',
        'The count of paid rows',
        'The sum of all rows',
        'The average',
        'Always NULL',
        'A CASE inside an aggregate conditionally counts rows.',
      ],
    ],
  },
  {
    id: 6,
    lecture: 'L6',
    theme: 'orbit-grand-prix',
    title: 'Orbit Grand Prix',
    // Module 6: window functions.
    questions: [
      [
        E,
        'Do window functions remove rows?',
        'No, they keep every row',
        'Yes',
        'Only ties',
        'Only with PARTITION',
        'Windows add a column without collapsing rows.',
      ],
      [
        M,
        'Window functions differ from GROUP BY because they…',
        'Keep every row while adding a computed column',
        'Always reduce rows',
        'Cannot use PARTITION',
        'Only sort',
        'Windows compute over a set of rows without collapsing them.',
      ],
      [
        M,
        'ROW_NUMBER() OVER (ORDER BY x) gives…',
        'A unique sequential number per row',
        'The same number to ties',
        'Group counts',
        'Random ids',
        'ROW_NUMBER is always distinct, even for ties.',
      ],
      [
        M,
        'After a tie, RANK() …',
        'Skips the next rank(s)',
        'Never skips',
        'Restarts at 1',
        'Equals ROW_NUMBER',
        'RANK leaves gaps after ties; DENSE_RANK does not.',
      ],
      [
        M,
        'After two tied first places, DENSE_RANK() gives the next row…',
        '2',
        '3',
        '1',
        '4',
        'DENSE_RANK has no gaps.',
      ],
      [
        M,
        'LAG(x) OVER (ORDER BY t) returns…',
        "The previous row's x",
        "The next row's x",
        'The current x',
        'NULL always',
        'LAG looks back one row in the ordering.',
      ],
      [
        M,
        'LEAD(x) OVER (ORDER BY t) returns…',
        "The next row's x",
        "The previous row's x",
        'The max x',
        'The first x',
        'LEAD looks ahead one row.',
      ],
      [
        M,
        'PARTITION BY dept in a window means…',
        'Restart the calculation per dept',
        'Filter by dept',
        'Join on dept',
        'Sort only',
        'PARTITION BY resets the window per group.',
      ],
      [
        M,
        'Which runs last in logical query order?',
        'ORDER BY',
        'FROM',
        'WHERE',
        'GROUP BY',
        'Order: FROM, WHERE, GROUP BY, HAVING, SELECT, ORDER BY.',
      ],
      [
        H,
        'A 3-row moving average uses which frame?',
        'ROWS BETWEEN 2 PRECEDING AND CURRENT ROW',
        'ROWS UNBOUNDED FOLLOWING',
        'no frame',
        'GROUP BY 3',
        'A rolling window frame defines which rows are averaged.',
      ],
      [
        H,
        'Can you filter on a window result in WHERE?',
        'No; wrap it in a subquery/CTE',
        'Yes, directly',
        'Only with HAVING alias',
        'Only in a view',
        'Window functions run after WHERE, so filter them later.',
      ],
    ],
  },
  {
    id: 7,
    lecture: 'L7',
    theme: 'nesting-temple',
    title: 'The Nesting Temple',
    // Module 7: subqueries, correlated vs non-correlated.
    questions: [
      [
        E,
        'A subquery is…',
        'A query nested inside another query',
        'A join',
        'An index',
        'A view',
        'A subquery is a query used within another statement.',
      ],
      [
        M,
        'A subquery in the WHERE clause typically…',
        'Filters rows using its result',
        'Chooses columns',
        'Creates a table',
        'Sorts output',
        'WHERE subqueries supply values or conditions to filter.',
      ],
      [
        M,
        'A subquery in the FROM clause acts as…',
        'A derived table',
        'A column',
        'A constraint',
        'A trigger',
        'A FROM subquery is a virtual table and must be aliased.',
      ],
      [
        M,
        'A scalar subquery in the SELECT list returns…',
        'A single value per row',
        'Many rows',
        'A whole table',
        'Nothing',
        'A subquery in SELECT must return one value.',
      ],
      [
        M,
        'A correlated subquery…',
        "References the outer query's current row",
        'Runs once in total',
        'Cannot use WHERE',
        'Is always faster',
        'A correlated subquery re-evaluates per outer row.',
      ],
      [
        M,
        'A non-correlated subquery…',
        'Can be evaluated once, independently',
        'Depends on outer rows',
        'Must use EXISTS',
        'Returns no rows',
        'It does not reference the outer query.',
      ],
      [
        M,
        'WHERE salary > (SELECT AVG(salary) FROM emp) is…',
        'A non-correlated scalar subquery',
        'A correlated subquery',
        'A join',
        'Invalid',
        'The inner query is independent and returns one value.',
      ],
      [
        H,
        "Which is usually best for 'has at least one match'?",
        'EXISTS (correlated)',
        'COUNT(*) > 0 in SELECT',
        'IN over all rows',
        'LEFT JOIN then DISTINCT',
        'EXISTS can stop at the first matching row.',
      ],
      [
        H,
        'Which subquery type generally cannot run standalone?',
        'Correlated',
        'Non-correlated',
        'Derived table',
        'Scalar in FROM',
        'A correlated subquery needs the outer row to run.',
      ],
    ],
  },
  {
    id: 8,
    lecture: 'L8',
    theme: 'noir-bureau',
    title: 'Noir Bureau',
    // Module 8: joins and set operations.
    questions: [
      [
        E,
        'An INNER JOIN returns…',
        'Only rows that match in both tables',
        'All rows from both',
        'Unmatched left rows',
        'Unmatched right rows',
        'INNER JOIN keeps only matching rows.',
      ],
      [
        E,
        'UNION combines two result sets and…',
        'Removes duplicate rows',
        'Keeps duplicates',
        'Requires a join',
        'Sorts by id',
        'UNION removes duplicates; UNION ALL keeps them.',
      ],
      [
        M,
        'A LEFT JOIN returns…',
        'All left rows plus matches (NULLs where none)',
        'Only matches',
        'All right rows',
        'The intersection',
        'LEFT JOIN keeps every left row.',
      ],
      [
        M,
        'A RIGHT JOIN returns…',
        'All right rows plus matches',
        'Only matches',
        'All left rows',
        'Nothing',
        'RIGHT JOIN keeps every right row.',
      ],
      [
        M,
        'A FULL OUTER JOIN returns…',
        'All rows from both, matched where possible',
        'Only matches',
        'Left rows only',
        'Right rows only',
        'FULL keeps unmatched rows from both sides.',
      ],
      [
        M,
        'A SELF JOIN is…',
        'A table joined to itself',
        'A join with no condition',
        'A cross join',
        'An outer join',
        'Self joins relate rows within one table using two aliases.',
      ],
      [
        M,
        'To keep customers who have no orders, use…',
        'LEFT JOIN orders',
        'INNER JOIN orders',
        'RIGHT JOIN orders',
        'CROSS JOIN orders',
        'LEFT JOIN preserves customers lacking orders.',
      ],
      [
        M,
        'Joining three tables needs…',
        'Two join conditions',
        'One condition',
        'No condition',
        'A UNION',
        'Each extra table adds a join condition.',
      ],
      [
        M,
        'UNION ALL differs from UNION because it…',
        'Keeps duplicates (and is faster)',
        'Removes duplicates',
        'Requires the same table',
        'Sorts results',
        'UNION ALL skips the de-duplication step.',
      ],
      [
        M,
        'INTERSECT returns…',
        'Rows present in both queries',
        'Rows in either query',
        'Rows in the first only',
        'All rows',
        'INTERSECT keeps the common rows.',
      ],
      [
        M,
        'Set operations require the two queries to have…',
        'The same number and types of columns',
        'The same table',
        'A join key',
        'An ORDER BY',
        'The column lists must be union-compatible.',
      ],
      [
        M,
        'A join condition usually compares…',
        'A foreign key to a primary key',
        'Two unrelated text columns',
        'Row counts',
        'Aggregates',
        'Joins match related keys across tables.',
      ],
      [
        H,
        'Omitting the join condition produces…',
        'A Cartesian product',
        'An error',
        'An inner join',
        'An empty set',
        'With no ON, every left row pairs with every right row.',
      ],
      [
        H,
        'For a LEFT JOIN, a WHERE filter on the right table can…',
        'Turn it into an inner join',
        'Do nothing',
        'Add rows',
        'Cause an error',
        'Filtering right columns in WHERE drops the NULL-extended rows.',
      ],
      [
        H,
        'Using INNER where LEFT was needed typically causes…',
        'Missing rows that had no match',
        'Extra duplicate rows',
        'A syntax error',
        'NULL keys',
        'INNER drops the unmatched rows a LEFT would keep.',
      ],
      [
        H,
        'Joining then summarizing is done by…',
        'JOIN first, then GROUP BY the result',
        'GROUP BY before FROM',
        'HAVING before JOIN',
        'GROUP BY inside ON',
        'Rows are joined, then grouped and aggregated.',
      ],
    ],
  },
  {
    id: 9,
    lecture: 'L10',
    theme: 'cartographers-finale',
    title: 'The Cartographer’s Finale',
    // Module 10: ER / data modelling.
    questions: [
      [
        E,
        'In an ER diagram, a rectangle usually represents an…',
        'Entity',
        'Attribute',
        'Relationship',
        'Cardinality',
        'Entities are drawn as rectangles.',
      ],
      [
        E,
        'An ellipse (oval) in ER notation represents an…',
        'Attribute',
        'Entity',
        'Relationship',
        'Key',
        'Attributes are ovals attached to entities.',
      ],
      [
        M,
        'A diamond in ER notation represents a…',
        'Relationship',
        'Entity',
        'Attribute',
        'Constraint',
        'Relationships are diamonds linking entities.',
      ],
      [
        M,
        'Cardinality 1:N means…',
        'One row on the left relates to many on the right',
        'Many-to-many',
        'One-to-one',
        'No relationship',
        '1:N is a one-to-many relationship.',
      ],
      [
        M,
        'A weak entity is one that…',
        'Cannot be identified without another entity',
        'Has no attributes',
        'Has no rows',
        'Is always 1:1',
        'A weak entity depends on an owner for its identity.',
      ],
      [
        M,
        'Total participation means…',
        'Every instance must take part in the relationship',
        'Some instances may take part',
        'No instance takes part',
        'Participation is optional',
        'Total (mandatory) participation requires every instance to join.',
      ],
      [
        M,
        'A many-to-many relationship is implemented in tables with…',
        'A junction / bridge table',
        'A single foreign key',
        'A CHECK constraint',
        'A view',
        'An associative table holds the two foreign keys.',
      ],
      [
        H,
        'The levels of data modelling, abstract to concrete, are…',
        'Conceptual, logical, physical',
        'Physical, logical, conceptual',
        'Logical, physical, conceptual',
        'Only physical',
        'Modelling proceeds conceptual, then logical, then physical.',
      ],
      [
        H,
        "A weak entity's key is formed by…",
        "Its partial key plus the owner's key",
        'Its partial key alone',
        'A surrogate only',
        'No key',
        'Weak entities combine a discriminator with the owner’s key.',
      ],
    ],
  },
];

const quote = (s) => "'" + String(s).replaceAll("'", "''") + "'";

let sql =
  '-- Generated by scripts/generate-seed.mjs from the DBMS 2026 topic tree.\n' +
  '-- Rounds map to lectures L1-L8 and L10; questions cover each module’s leaf\n' +
  '-- topics. Reviewable starter pool. Re-running replaces the whole pool.\n' +
  'begin;\n' +
  'delete from public.options;\n' +
  'delete from public.questions;\n' +
  'insert into public.rounds as r values\n' +
  rounds
    .map(
      (x) =>
        `(${x.id},${quote(x.lecture)},${quote(x.theme)},${quote(x.title)})`,
    )
    .join(',\n') +
  '\non conflict (id) do update set lecture=excluded.lecture, theme_key=excluded.theme_key, title=excluded.title;\n';

for (const round of rounds) {
  for (const [
    difficulty,
    stem,
    correct,
    d1,
    d2,
    d3,
    explanation,
  ] of round.questions) {
    sql +=
      `with q as (insert into public.questions(round_id,display_type,difficulty,stem,explanation) values(${round.id},'concept',${quote(difficulty)},${quote(stem)},${quote(explanation)}) returning id)\n` +
      'insert into public.options(question_id,body,is_correct,misconception) select q.id,v.body,v.correct,v.misconception from q cross join (values\n' +
      [correct, d1, d2, d3]
        .map(
          (text, i) =>
            `(${quote(JSON.stringify({ text }))}::jsonb,${i === 0},${i === 0 ? 'null' : quote(`Confuses ${correct} with ${text}`)})`,
        )
        .join(',\n') +
      ') v(body,correct,misconception);\n';
  }
}
sql += 'commit;\n';

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql);

const counts = rounds.map((r) => `R${r.id}=${r.questions.length}`).join(' ');
console.log(
  `Wrote supabase/seed.sql: ${counts} (total ${rounds.reduce((n, r) => n + r.questions.length, 0)})`,
);
